/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        background: '#111318',
        surface: '#111318',
        'surface-dim': '#111318',
        'surface-bright': '#37393e',
        'surface-container-lowest': '#0c0e12',
        'surface-container-low': '#191c20',
        'surface-container': '#1d2024',
        'surface-container-high': '#282a2f',
        'surface-container-highest': '#333539',
        'surface-variant': '#333539',
        'on-surface': '#e2e2e8',
        'on-surface-variant': '#bac9cc',
        'inverse-surface': '#e2e2e8',
        'inverse-on-surface': '#2e3035',
        outline: '#849396',
        'outline-variant': '#3b494c',
        'surface-tint': '#00daf3',
        primary: '#c3f5ff',
        'on-primary': '#00363d',
        'primary-container': '#00e5ff',
        'on-primary-container': '#00626e',
        'inverse-primary': '#006875',
        'primary-fixed': '#9cf0ff',
        'primary-fixed-dim': '#00daf3',
        'on-primary-fixed': '#001f24',
        'on-primary-fixed-variant': '#004f58',
        secondary: '#c4c6d0',
        'on-secondary': '#2d3038',
        'secondary-container': '#464951',
        'on-secondary-container': '#b6b8c2',
        'secondary-fixed': '#e0e2ec',
        'secondary-fixed-dim': '#c4c6d0',
        'on-secondary-fixed': '#191c23',
        'on-secondary-fixed-variant': '#44474f',
        tertiary: '#ffeac0',
        'on-tertiary': '#3e2e00',
        'tertiary-container': '#fec931',
        'on-tertiary-container': '#6f5500',
        'tertiary-fixed': '#ffdf96',
        'tertiary-fixed-dim': '#f3bf26',
        'on-tertiary-fixed': '#251a00',
        'on-tertiary-fixed-variant': '#594400',
        error: '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
        'text-primary': '#F5F7FA',
        'text-muted': '#606D7A',
        'risk-urgent': '#FF3B30',
        'risk-high': '#FF9500',
        'risk-medium': '#FFCC00',
        'risk-low': '#2C3139',
        vultra: {
          bg: '#111318',
          panel: '#191c20',
          surface: '#1d2024',
          border: '#3b494c',
          accent: '#00e5ff',
          accentGlow: 'rgba(0, 229, 255, 0.15)',
        },
      },
      borderRadius: {
        DEFAULT: '0px',
        none: '0px',
        sm: '0px',
        md: '0px',
        lg: '0px',
        xl: '0px',
        '2xl': '0px',
        '3xl': '0px',
        full: '9999px',
      },
      spacing: {
        margin: '40px',
        unit: '4px',
        gutter: '24px',
        'section-gap': '80px',
      },
      fontFamily: {
        sans: ['Geist', 'Inter', 'system-ui', '-apple-system', 'sans-serif'],
        mono: ['JetBrains Mono', 'Fira Code', 'monospace'],
        display: ['Geist', 'sans-serif'],
        'display-lg': ['Geist', 'sans-serif'],
        'headline-lg': ['Geist', 'sans-serif'],
        'headline-lg-mobile': ['Geist', 'sans-serif'],
        'headline-md': ['Geist', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'label-caps': ['Geist', 'sans-serif'],
      },
      fontSize: {
        'display-lg': ['64px', { lineHeight: '1.0', letterSpacing: '-0.04em', fontWeight: '700' }],
        'headline-lg': ['32px', { lineHeight: '1.1', letterSpacing: '-0.03em', fontWeight: '600' }],
        'headline-lg-mobile': ['24px', { lineHeight: '1.2', letterSpacing: '-0.02em', fontWeight: '600' }],
        'headline-md': ['20px', { lineHeight: '1.3', letterSpacing: '-0.01em', fontWeight: '500' }],
        'body-lg': ['16px', { lineHeight: '1.6', letterSpacing: '0', fontWeight: '400' }],
        'body-md': ['14px', { lineHeight: '1.5', letterSpacing: '0', fontWeight: '400' }],
        'label-caps': ['11px', { lineHeight: '1.4', letterSpacing: '0.1em', fontWeight: '600' }],
      },
      animation: {
        'pulse-subtle': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'fade-slide-up': 'fadeSlideUp 0.4s cubic-bezier(0.4, 0, 0.2, 1) forwards',
      },
      keyframes: {
        fadeSlideUp: {
          '0%': { opacity: '0', transform: 'translateY(8px)' },
          '100%': { opacity: '1', transform: 'translateY(0)' },
        },
      },
    },
  },
  plugins: [],
};
